version: '3.8'

services:
  traefik:
    image: traefik:v2.6
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=your-email@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Interface Traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
    networks:
      - web
    deploy:
      replicas: 1

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static  # Assurez-vous que les fichiers statiques sont générés et présents ici
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`panelart.fun`)"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls.certresolver=myresolver"
    depends_on:
      - web
    networks:
      - web
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  web:
    image: dufi1928/eduathena-backend:latest
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}  # Utiliser les informations de la base de données déjà déployée
      - DB_PORT=${DB_PORT}  # Port de connexion à la base de données
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`api.panelart.fun`)"  # Sous-domaine pour le backend
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
    networks:
      - web
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  web:

volumes:
  letsencrypt:
